<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lokasi1 extends CI_Controller
{


    function __construct()
    {

        parent::__construct();
        if (!$this->ion_auth->logged_in()){
  			redirect('auth');	}
        else if (!$this->ion_auth->in_group('Operator') && !$this->ion_auth->is_admin()){
          show_error('Hanya Administrator yang diberi hak untuk mengakses halaman ini, <a href="'.base_url('dashboard').'">Kembali ke menu awal</a>', 403, 'Akses Terlarang');
        }

        $this->load->model('Gedung_model');
        $this->load->library('form_validation');
        $this->user = $this->ion_auth->user()->row();
    }

    public function messageAlert($type, $title) {
      $messageAlert = "
      const Toast = Swal.mixin({
          toast: true,
          position: 'top-end',
          showConfirmButton: false,
          timer: 5000
      });

      Toast.fire({
          type: '".$type."',
          title: '".$title."'
      });
      ";
      return $messageAlert;
  }

    public function index()
    {
        $user = $this->user;
        $gedung = $this->Gedung_model->get_all();

        $data = array(
            'gedung_data' => $gedung,
            'user' => $user,
            'users' 	=> $this->ion_auth->user()->row(),
        );

        $this->template->load('template','lokasi_list1', $data);
    }

    public function read($id)
    {
        $user = $this->user;
        $gedung = $this->Gedung_model->get_by_id_q($id);

            $data = array(
    'gedung_data' => $gedung,
    'user' => $user,
    'users' 	=> $this->ion_auth->user()->row(),
	    );
      $this->template->load('template','gedung_read1', $data);

    }



}

/* End of file Gedung.php */
/* Location: ./application/controllers/Gedung.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-18 06:59:08 */
/* http://harviacode.com */
