<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barcode_model extends CI_Model
{

    public $table = 'barcode';
    public $id = 'id_barcode';
    public $order = 'DESC';
    public $id_karyawan = 'id_karyawan';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_barcode', $q);
	$this->db->or_like('id_karyawan', $q);
	$this->db->or_like('qr_code', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_barcode', $q);
	$this->db->or_like('id_karyawan', $q);
	$this->db->or_like('qr_code', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data,$image_name)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Barcode_model.php */
/* Location: ./application/models/Barcode_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-20 04:40:35 */
/* http://harviacode.com */